extends: spectral:oas
rules:
  adidas-paths-kebab-case:
    description: All endpoints/paths MUST follow kebab-case
    severity: error
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^\/([a-z0-9]+(-[a-z0-9]+))?(\/[a-z0-9]+(-[a-z0-9]+)|\/{.+})*$"
