extends: spectral:oas
functions:
  - dictionary
rules:
  no-evil-words:
    message: "error"
    given:
      - $.info.title
      - $.info.description
    severity: error
    then:
      function: "dictionary"
