extends: spectral:oas
functions:
  - dictionary
rules:
  no-evil-words:
    message: "error"
    severity: error
    given:
      - "$.info.title"
      - "$.info.description"
    then:
      function: "dictionary"
